In [1]:
import pandas as pd
fd=pd.read_csv("diabetes.csv")
print(fd)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age  Outcome
0                       0.627   50        1
1                       0.351   31        0
2                       0.672   32        1
3                       0.167   21        0
4                       2.288   33        1
..                        ...  ...      ...
763                     0.171   63        0
764                     0.340   27        0
765                     0.245   30        0
766                     0.349   47        1
767                     0.315   23        0

[768 rows x 9 columns]

In [2]:
people={
    "first":["mohan","james","swara"],
    "last":["rao","nick","laasya"],
    "email":["mohanrrao@gmail.com","jamesnic@gmail.com","swaralaasya@gmail.com"]
}

In [3]:
people
type(people)

dict

In [4]:
df=pd.DataFrame(people)

In [5]:
df.email

0      mohanrrao@gmail.com
1       jamesnic@gmail.com
2    swaralaasya@gmail.com
Name: email, dtype: object

In [6]:
df.columns

Index(['first', 'last', 'email'], dtype='object')

In [7]:
df

   first    last                  email
0  mohan     rao    mohanrrao@gmail.com
1  james    nick     jamesnic@gmail.com
2  swara  laasya  swaralaasya@gmail.com

In [8]:
# iloc - index location
df.iloc[0]

first                  mohan
last                     rao
email    mohanrrao@gmail.com
Name: 0, dtype: object

In [9]:
df.iloc[1]

first                 james
last                   nick
email    jamesnic@gmail.com
Name: 1, dtype: object

In [10]:
df.iloc[0,1]

'rao'

In [11]:
df.iloc[[0,1],[1,2]]

   last                email
0   rao  mohanrrao@gmail.com
1  nick   jamesnic@gmail.com

In [12]:
df.reset_index(inplace=True)

In [13]:
df.set_index["email",inplace==True]

NameError: name 'inplace' is not defined