In [98]:
import pandas as pd

In [99]:
df=pd.read_csv('smaller_adult.csv')
df=pd.DataFrame(df)

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3574 entries, 0 to 3573
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              3574 non-null   int64
 1   workclass        3574 non-null   object
 2   educational-num  3574 non-null   int64
 3   occupation       3574 non-null   object
 4   gender           3574 non-null   object
 5   hours-per-week   3574 non-null   int64
 6   income           3574 non-null   object
dtypes: int64(3), object(4)
memory usage: 195.6+ KB

In [101]:
df.isnull().sum()

age                0
workclass          0
educational-num    0
occupation         0
gender             0
hours-per-week     0
income             0
dtype: int64

In [102]:
df=df.drop_duplicates()

In [103]:
y=df['income']
x=df.drop(['income'],axis=1)

In [104]:
from sklearn.preprocessing import LabelEncoder
y=LabelEncoder().fit_transform(y)
y=pd.DataFrame(y)
y

      0
0     0
1     0
2     1
3     1
4     0
...  ..
3317  0
3318  1
3319  0
3320  1
3321  1

[3322 rows x 1 columns]

In [105]:
#tak
numerical_features=x.select_dtypes('number')
catagorical_features=x.select_dtypes('object')
numerical_features

      age  educational-num  hours-per-week
0      25                7              40
1      38                9              50
2      28               12              40
3      44               10              40
4      18               10              30
...   ...              ...             ...
3569   49                9              40
3570   29               11              40
3571   25                9              50
3572   47                9              50
3573   44               13              60

[3322 rows x 3 columns]

In [106]:
converted_catagorical_features=pd.get_dummies(catagorical_features)
all_features=[converted_catagorical_features,numerical_features]
newX=pd.concat(all_features,axis=1,join='inner')
converted_catagorical_features.shape

(3322, 25)

In [107]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(newX,y,test_size=0.3)

In [108]:
from sklearn.svm import SVC
model=SVC(kernel='linear',gamma='auto').fit(x_train,y_train)

/usr/local/lib/python3.11/site-packages/sklearn/utils/validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [109]:
y_pred=model.predict(x_test)

In [110]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7662988966900702